#!/usr/bin/env bash
# Regenerate docs/handoff/DATABASE_SCHEMA.md from the running local database.
#
# CLAUDE.md forbids hand-editing that file: it is a record of what the database
# actually is, and a hand-edit turns it back into prose that can be wrong. Run
# this after applying a migration instead.
#
#   ./scripts/dump_schema.sh
#
# Requires the local Supabase stack to be up (`npx supabase start`).
set -euo pipefail

CONTAINER=supabase_db_aiot-school-lab
OUT="$(dirname "$0")/../docs/handoff/DATABASE_SCHEMA.md"

# `< /dev/null` matters: these run inside `while read` loops, and without it
# the inner psql consumes the loop's own input and the dump silently truncates.
psql() { docker exec "$CONTAINER" psql -U postgres -d postgres -At -F'|' -q -c "$1" < /dev/null; }

LATEST=$(ls "$(dirname "$0")/../supabase/migrations" | tail -1)
COUNTS=$(psql "
  select
    count(*) filter (where c.relkind in ('r','p','v','m')),
    count(*) filter (where c.relkind in ('r','p')),
    count(*) filter (where c.relkind in ('v','m'))
  from pg_class c join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public';")
TOTAL=$(cut -d'|' -f1 <<<"$COUNTS")
TABLES=$(cut -d'|' -f2 <<<"$COUNTS")
VIEWS=$(cut -d'|' -f3 <<<"$COUNTS")

{
  echo "# Database Schema"
  echo
  echo "_Live dump from local Supabase, regenerated $(date +%Y-%m-%d) after applying all migrations through \`$LATEST\`._"
  echo
  echo "Generated by \`./scripts/dump_schema.sh\` — do not hand-edit."
  echo
  echo "Total relations: $TOTAL ($TABLES tables, $VIEWS views/materialized views)"
  echo
  echo "RLS and direct grants must still be evaluated together. The main app uses custom-session SECURITY DEFINER RPCs; this document records the live final schema and function signatures."
  echo

  psql "
    select c.relname, c.relkind, c.relrowsecurity
      from pg_class c join pg_namespace n on n.oid = c.relnamespace
     where n.nspname = 'public' and c.relkind in ('r','p','v','m')
     order by c.relname;" |
  while IFS='|' read -r rel kind rls; do
    case "$kind" in
      v|m) echo "## $rel (view)";;
      *)   echo "## $rel"; echo; echo "RLS enabled: **$rls**";;
    esac
    echo
    echo '| column | type | nullable | default |'
    echo '|---|---|---|---|'
    psql "
      select column_name, data_type, is_nullable, coalesce(column_default, '')
        from information_schema.columns
       where table_schema = 'public' and table_name = '$rel'
       order by ordinal_position;" |
      while IFS='|' read -r col type nul def; do
        echo "| $col | $type | $nul | $def |"
      done
    fks=$(psql "
      select kcu.column_name || ' -> ' || ccu.table_name || '.' || ccu.column_name
        from information_schema.table_constraints tc
        join information_schema.key_column_usage kcu
          on kcu.constraint_name = tc.constraint_name
         and kcu.table_schema = tc.table_schema
        join information_schema.constraint_column_usage ccu
          on ccu.constraint_name = tc.constraint_name
         and ccu.table_schema = tc.table_schema
       where tc.table_schema = 'public'
         and tc.table_name = '$rel'
         and tc.constraint_type = 'FOREIGN KEY'
       order by kcu.column_name;")
    if [ -n "$fks" ]; then
      echo
      echo "Foreign keys:"
      while IFS= read -r fk; do echo "- $fk"; done <<<"$fks"
    fi
    echo
  done

  echo "## RPC and function signatures"
  echo
  psql "
    select p.proname
        || '(' || pg_get_function_arguments(p.oid) || ') -> '
        || pg_get_function_result(p.oid)
        || ' (' || case when p.prosecdef then 'SECURITY DEFINER' else 'SECURITY INVOKER' end
        || ', ' || l.lanname || ')'
      from pg_proc p
      join pg_namespace n on n.oid = p.pronamespace
      join pg_language l on l.oid = p.prolang
     where n.nspname = 'public' and l.lanname in ('sql','plpgsql')
     order by p.proname, pg_get_function_arguments(p.oid);" |
  while IFS= read -r sig; do
    echo "### $sig"
    echo
  done
} > "$OUT"

echo "wrote $OUT ($(wc -l < "$OUT") lines)"
